apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: airshipclusterproviderspecs.airshipprovider.airshipit.org
spec:
  group: airshipprovider.airshipit.org
  names:
    kind: AirshipClusterProviderSpec
    plural: airshipclusterproviderspecs
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        caCertificate:
          description: CACertificate is a PEM encoded CA Certificate for the control
            plane nodes.
          format: byte
          type: string
        caKey:
          description: CAPrivateKey is a PEM encoded PKCS1 CA PrivateKey for the control
            plane nodes.
          format: byte
          type: string
        deploymentConfiguration:
          description: Shiyard DeploymentConfiguration
          properties:
            armada:
              properties:
                getReleasesTimeout:
                  format: int64
                  type: integer
                getStatusTimeout:
                  format: int64
                  type: integer
                manifest:
                  type: string
                postApplyTimeout:
                  format: int64
                  type: integer
                validateDesignTimeout:
                  format: int64
                  type: integer
              required:
              - manifest
              type: object
            kubernetes:
              properties:
                nodeStatusInterval:
                  format: int64
                  type: integer
                nodeStatusTimeout:
                  format: int64
                  type: integer
              type: object
            kubernetesProvisioner:
              properties:
                clearLabelsTimeout:
                  format: int64
                  type: integer
                drainGracePeriod:
                  format: int64
                  type: integer
                drainTimeout:
                  format: int64
                  type: integer
                etcdReadyTimeout:
                  format: int64
                  type: integer
                removeEtcdTimeout:
                  format: int64
                  type: integer
              type: object
            physicalProvisioner:
              properties:
                deployInterval:
                  format: int64
                  type: integer
                deployTimeout:
                  format: int64
                  type: integer
                deploymentStrategy:
                  type: string
                destroyInterval:
                  format: int64
                  type: integer
                destroyTimeout:
                  format: int64
                  type: integer
                joinWait:
                  format: int64
                  type: integer
                prepareNodeInterval:
                  format: int64
                  type: integer
                prepareNodeTimeout:
                  format: int64
                  type: integer
                prepareSiteInterval:
                  format: int64
                  type: integer
                prepareSiteTimeout:
                  format: int64
                  type: integer
                relabelNodesInterval:
                  format: int64
                  type: integer
                relabelNodesTimeout:
                  format: int64
                  type: integer
                verifyInterval:
                  format: int64
                  type: integer
                verifyTimeout:
                  format: int64
                  type: integer
              type: object
          required:
          - armada
          type: object
        deploymentStrategy:
          properties:
            groups:
              items:
                properties:
                  critical:
                    type: boolean
                  dependsOn:
                    items:
                      type: string
                    type: array
                  name:
                    type: string
                  selectors:
                    items:
                      properties:
                        nodeLabels:
                          items:
                            type: string
                          type: array
                        nodeNames:
                          items:
                            type: string
                          type: array
                        nodeTags:
                          items:
                            type: string
                          type: array
                        rackNames:
                          items:
                            type: string
                          type: array
                      type: object
                    type: array
                  successCriteria:
                    properties:
                      maximumFailedNodes:
                        format: int64
                        type: integer
                      minimumSuccessfulNodes:
                        format: int64
                        type: integer
                      percentSuccessfulNodes:
                        format: int64
                        type: integer
                    type: object
                required:
                - critical
                - dependsOn
                - name
                - selectors
                type: object
              type: array
          required:
          - groups
          type: object
        hardwareProfiles:
          description: 'Drydock Configuration JEB: This is common configuration for
            the hardware. Force to add it to the cluster for right now.'
          items:
            properties:
              biosVersion:
                type: string
              bootMode:
                type: string
              bootstrapProtocol:
                type: string
              cpuSets:
                type: object
              deviceAliases:
                type: object
              generation:
                type: string
              hugepages:
                type: object
              hwVersion:
                type: string
              pxeInterface:
                format: double
                type: number
              vendor:
                type: string
            type: object
          type: array
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        location:
          type: string
        metadata:
          type: object
        networks:
          description: 'JEB: This is network configuration. The generic cluster definition
            account s for CNI/calico setup up, but does describe the underlying network.'
          items:
            properties:
              cidr:
                type: string
              dhcpRelay:
                properties:
                  selfIp:
                    type: string
                  upstreamTarget:
                    type: string
                type: object
              dns:
                properties:
                  domain:
                    type: string
                  servers:
                    type: string
                type: object
              labels:
                type: object
              mtu:
                format: double
                type: number
              ranges:
                items:
                  properties:
                    end:
                      type: string
                    start:
                      type: string
                    type:
                      type: string
                  type: object
                type: array
              routedomain:
                type: string
              routes:
                items:
                  properties:
                    gateway:
                      type: string
                    metric:
                      format: double
                      type: number
                    routedomain:
                      type: string
                    subnet:
                      type: string
                  type: object
                type: array
              vlan:
                type: string
            type: object
          type: array
        resourceGroup:
          type: string
      required:
      - resourceGroup
      - location
      - deploymentConfiguration
      - deploymentStrategy
      - hardwareProfiles
      - networks
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
