apiVersion: "cluster.k8s.io/v1alpha1"
kind: Cluster
metadata:
  name: simple
spec:
  clusterNetwork:
    services:
      cidrBlocks: ["10.96.0.0/12"]
    pods:
      cidrBlocks: ["192.168.0.0/16"]
    serviceDomain: "cluster.local"
  providerSpec:
    value:
      apiVersion: "airshipprovider/v1alpha1"
      kind: "AirshipClusterProviderSpec"
      # resourceGroup: "${RESOURCE_GROUP}"
      # location: "${LOCATION}"
