apiVersion: "cluster.k8s.io/v1alpha1"
kind: MachineList
items:
  - apiVersion: "cluster.k8s.io/v1alpha1"
    kind: Machine
    metadata:
      name: controlplane-0
      labels:
        set: controlplane
    spec:
      versions:
        kubelet: 1.13.3
        controlPlane: 1.13.3
      providerSpec:
        value:
          apiVersion: airshipprovider/v1alpha1
          kind: AirshipMachineProviderSpec
          roles:
          - Master
          location: ${LOCATION}
          vmSize: ${CONTROL_PLANE_MACHINE_TYPE}
          image:
            publisher: "Canonical"
            offer: "UbuntuServer"
            sku: "16.04-LTS"
            version: "latest"
          osDisk:
            osType: "Linux"
            managedDisk:
              storageAccountType: "Premium_LRS"
            diskSizeGB: 30
          sshPublicKey: ${SSH_PUBLIC_KEY}
          sshPrivateKey: ${SSH_PRIVATE_KEY}
  - apiVersion: "cluster.k8s.io/v1alpha1"
    kind: Machine
    metadata:
      generateName: node-
      labels:
        set: node
    spec:
      versions:
        kubelet: 1.12.5
      providerSpec:
        value:
          apiVersion: airshipprovider/v1alpha1
          kind: AirshipMachineProviderSpec
          roles:
          - Node
          location: ${LOCATION}
          vmSize: ${NODE_MACHINE_TYPE}
          image:
            publisher: "Canonical"
            offer: "UbuntuServer"
            sku: "16.04-LTS"
            version: "latest"
          osDisk:
            osType: "Linux"
            managedDisk:
              storageAccountType: "Premium_LRS"
            diskSizeGB: 30
          sshPublicKey: ${SSH_PUBLIC_KEY}
          sshPrivateKey: ${SSH_PRIVATE_KEY}
